name: Benchmark

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Run benchmarks daily at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      benchmark_filter:
        description: "Benchmark filter (e.g., SearchBenchmarks)"
        required: false
        default: ""

jobs:
  benchmark:
    # Use specific runner for consistent benchmark results
    runs-on: ubuntu-22.04 # 4 cores, 16GB RAM, consistent specs
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need full history for ASV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install UV
        uses: astral-sh/setup-uv@v2

      - name: Install ASV
        run: uv tool install asv

      - name: Initialize ASV environment
        run: |
          # Create ASV directory structure
          mkdir -p .asv/results
          mkdir -p .asv/html
          mkdir -p .asv/env

          echo "ASV directory structure created:"
          ls -la .asv/ || true

      - name: Download previous benchmark results
        uses: actions/download-artifact@v4
        with:
          name: asv-results
          path: .asv
        continue-on-error: true

      - name: Setup ASV machine
        run: |
          # Get actual system specifications from the runner
          CPU_INFO=$(lscpu | grep "Model name" | cut -d: -f2 | sed 's/^[ \t]*//' | head -1)
          CPU_COUNT=$(nproc)
          RAM_MB=$(free -m | grep "Mem:" | awk '{print $2}')
          RAM_GB=$((RAM_MB / 1024))
          ARCH=$(uname -m)

          # Get OS details
          OS_VERSION=$(lsb_release -ds 2>/dev/null | tr -d '"' || echo "Unknown")

          echo "Detected system specifications:"
          echo "  CPU: $CPU_INFO"
          echo "  Cores: $CPU_COUNT"
          echo "  RAM: ${RAM_GB}GB"
          echo "  Arch: $ARCH"
          echo "  OS: $OS_VERSION"

          # Create machine name from key specs to detect hardware changes
          # Format: ghactions-{arch}-{cores}c-{ram}gb
          MACHINE_NAME="ghactions-${ARCH}-${CPU_COUNT}c-${RAM_GB}gb"
          echo "Machine name: $MACHINE_NAME"

          # Configure machine with detected specs
          asv machine \
            --machine "$MACHINE_NAME" \
            --os "$OS_VERSION" \
            --arch "$ARCH" \
            --cpu "$CPU_INFO" \
            --num_cpu "$CPU_COUNT" \
            --ram "${RAM_GB}GB" \
            --yes

          # Store machine name for benchmark run
          echo "MACHINE_NAME=$MACHINE_NAME" >> $GITHUB_ENV

      - name: Run benchmarks
        run: |
          # Verify machine is configured
          echo "Using machine: $MACHINE_NAME"

          # Run benchmarks
          if [ -n "${{ github.event.inputs.benchmark_filter }}" ]; then
            echo "Running filtered benchmarks: ${{ github.event.inputs.benchmark_filter }}"
            asv run --python=3.12 --machine "$MACHINE_NAME" -b "${{ github.event.inputs.benchmark_filter }}" --verbose
          else
            echo "Running benchmarks for HEAD^!"
            asv run --python=3.12 --machine "$MACHINE_NAME" HEAD^! --verbose
          fi

          # Check results
          echo "Benchmark results:"
          ls -la .asv/ || true
          if [ -d ".asv/results" ]; then
            ls -la .asv/results/ || true
          fi

      - name: Show benchmark results on failure
        if: failure()
        run: |
          echo "Benchmark run failed. Checking for logs..."
          find .asv -name "*.log" -exec echo "=== {} ===" \; -exec cat {} \; || true
          echo "Checking ASV results directory..."
          ls -la .asv/ || true
          echo "Checking if schema files exist..."
          ls -la imas_mcp/resources/schemas/ || true

      - name: Generate HTML report
        run: |
          echo "Generating ASV HTML report..."
          asv publish

          echo "Checking generated files..."
          ls -la .asv/ || true
          if [ -d ".asv/html" ]; then
            echo "HTML directory contents:"
            ls -la .asv/html/ || true
          fi
          if [ -d ".asv/results" ]; then
            echo "Results directory contents:"
            ls -la .asv/results/ || true
          fi

      - name: Check ASV results before upload
        run: |
          echo "Checking ASV directory structure..."
          if [ -d ".asv" ]; then
            echo "✅ .asv directory exists"
            ls -la .asv/
            if [ -d ".asv/results" ]; then
              echo "✅ .asv/results directory exists"
              ls -la .asv/results/
            else
              echo "❌ .asv/results directory missing"
            fi
          else
            echo "❌ .asv directory does not exist"
          fi

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: asv-results
          path: .asv
          retention-days: 90
          if-no-files-found: ignore

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .asv/html
          destination_dir: benchmarks
          keep_files: false

      - name: Comment PR with benchmark results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = '.asv/html/index.json';

            if (fs.existsSync(path)) {
              const results = JSON.parse(fs.readFileSync(path, 'utf8'));
              const benchmarkUrl = `https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/benchmarks/`;
              
              const body = `## 📊 Benchmark Results
              
              Performance benchmarks have been run for this PR.
              
              🔗 **[View full benchmark report](${benchmarkUrl})**
              
              > Results are compared against the main branch. Significant changes will be highlighted in the full report.
              `;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              });
            }
