name: Performance Benchmarks

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Run benchmarks daily at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:
    inputs:
      benchmark_filter:
        description: "Benchmark filter (e.g., SearchBenchmarks)"
        required: false
        default: ""

jobs:
  benchmark:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need full history for ASV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install UV
        uses: astral-sh/setup-uv@v2

      - name: Install dependencies
        run: |
          uv sync --extra bench

      - name: Download previous benchmark results
        uses: actions/download-artifact@v4
        with:
          name: asv-results
          path: .asv
        continue-on-error: true

      - name: Setup ASV machine
        run: |
          source .venv/bin/activate
          asv machine --yes

      - name: Run benchmarks
        run: |
          source .venv/bin/activate
          if [ -n "${{ github.event.inputs.benchmark_filter }}" ]; then
            asv run --python=3.12 -b "${{ github.event.inputs.benchmark_filter }}"
          else
            asv run --python=3.12 HEAD^!
          fi

      - name: Generate HTML report
        run: |
          source .venv/bin/activate
          asv publish

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: asv-results
          path: .asv
          retention-days: 90

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .asv/html
          destination_dir: benchmarks
          keep_files: false

      - name: Comment PR with benchmark results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = '.asv/html/index.json';

            if (fs.existsSync(path)) {
              const results = JSON.parse(fs.readFileSync(path, 'utf8'));
              const benchmarkUrl = `https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/benchmarks/`;
              
              const body = `## 📊 Benchmark Results
              
              Performance benchmarks have been run for this PR.
              
              🔗 **[View full benchmark report](${benchmarkUrl})**
              
              > Results are compared against the main branch. Significant changes will be highlighted in the full report.
              `;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
              });
            }
